import Layout from "../components/layout";
import ExperienceList from "../components/experience-list";

const workExperience = [
  {
    role: "Senior Data Engineer/Tech Lead",
    company: "American Tire Distributors",
    location: "Remote",
    dates: "2022/02 - present",
    descriptionList: [
      "Architected and built entire ELT pipeline for ingesting data from an ERP system to internal data warehouse.",
      "Architected a client-facing app that reduced the bytes processed of vital queries from scale of GB to MB, resulting in reduced costs by 99%.",
      "Developed a data pipeline for insights app that reduced the required data generated by 90%, leading to improved performance.",
      "Built a scoring and leaderboard app for organization's 2022 hackathon event within 2 weeks. App was praised for being 'literally bulletproof' and acknowledged by event sponsors.",
      "Built a full-stack dashboard app in FastAPI and React that led to a lunch-n-learn session for the engineering teams.",
      "Host weekly tech review sessions for broader organization to discuss various technical topics and share knowledge.",
      "Lead a team of engineers and analysts; work with product stakeholders; make technical decisions for team.",
    ],
  },
  {
    role: "Lead Engineer",
    company: "Sunlight Medical",
    location: "Jacksonville, FL USA",
    dates: "2019/07 - 2022/02",
    descriptionList: [
      "Designed and developed a home-grown ERP mobile-friendly application that was received well by stakeholders. It reduced administrative costs by 90%. Used ReactJS, Django, PostgreSQL, Neo4j, and deployed onto Linux server using Docker.",
      "Developed a data submission application that automatically filled and submitted forms on the FDA GUDID website. It completely eliminated the need for a human to submit data through the website. Used Python and Selenium.",
      "Designed and developed an image grading application to process and rate microscope images of pipette tips. Responsible for data collection, data labeling, data pre-processing, and building the machine learning algorithm. Used Python, scikit-image, scikit-learn, OpenCV, and LabelBox.",
      "Helped troubleshoot and resolve networking issues within the manufacturing facility by working with a telecom provider, with an average turnaround time of 1 hour.",
      "Manage and maintain server, in-house software, and IoT hardware.",
      "Provide solutions and decisions to leadership regarding IT security and hardware provisioning.",
    ],
  },
  {
    role: "Freelance Developer/Data Scientist",
    company: "Self-employed",
    location: "Remote",
    dates: "2019/04 - present",
    descriptionList: [
      "Developed an app for applying mosaic censorship to facial features in videos. It utilized multi-threading for applying frame-by-frame censorship, resulting in quicker processing times. Used Python, numpy, and OpenCV.",
      "Developed multiple Python-based ETL scripts for a banking entity. Script reduced execution time of ETL processes by 15-25%.",
      "Designed and developed a customer-facing website for a fertility company. Used PHP, Bootstrap, and OctoberCMS.",
      "Contributed to a Django project that has 400+ GitHub stars. Wrote documentation, identified bugs, and suggested fixes for bugs.",
      "Built asset generator and web frontend of a NFT project. Led to sale of all 8888 NFTs within 24 hours. Website at https://spacepandaz.com",
    ],
  },
  {
    role: "Data Analyst",
    company: "Ubisoft Massive",
    location: "Malmo, Sweden",
    dates: "2017/11 - 2019/03",
    descriptionList: [
      "Developed a forecasting app in R Shiny that provides acquisition, activity, and concurrency forecasts for live producers. It reduced the time to generate forecasts from 40 hours to 1 minute. Responsible for entire app development. I talked about the app during the 2018 Nordic Data Science & Machine Learning Summit.",
      "Designed and developed a recommendation engine for a live game. Worked closely with game developers to gather data and build a data pipeline for providing the recommendations.",
      "Optimized a report generation tool for a live game in Python that reduced generation time by 50%.",
      "Optimized and improved the monetization data pipeline for a live game, cutting ETL runtime by 98%.",
      "Hosted a teaching session with a colleague to inspire high school students to join the video game industry as a data scientist. The session was so well received that they requested to do it again the following year.",
      "Mentored other analysts by reviewing their code, providing learning materials for their self-development goals, and helping them with their projects.",
    ],
  },
  {
    role: "Data Analyst, Data Scientist",
    company: "Florida Blue",
    location: "Jacksonville, FL USA",
    dates: "2012/03 - 2017/09",
    descriptionList: [
      "Developed and deployed 3 models for identifying real-time events that contributed to rising cost and risk. Used Python and scikit-learn. Models helped nurses identify members who were within 1-3 months of becoming high risk.",
      "Developed a survey application that records audience answers from their mobile phones. It received recognition from leadership for its innovative concept of testing audience knowledge. Used Flask and Plivo API.",
      "Developed an online report platform in Flask that automatically generates reports and dashboards for stakeholders.",
      "Developed a database crawler in SAS that provided recommendations of tables and fields based on analysts’ queries. It reduced IT support tickets by 20%.",
      "Helped design and develop an A/B test for evaluating care programs. Used propensity score matching and written in SAS.",
      "Mentored and trained other analysts in Python data analysis.",
      "Acted as SAS programming coach for my team by providing efficient coding techniques, solutions to complex queries, and macro code for automation.",
    ],
  },
];

function Heading({ children }) {
  return (
    <h2 className="mb-4 text-lg font-bold tracking-tight text-primary-600 dark:text-primary-500 sm:text-xl">
      {children}
    </h2>
  );
}

function TRow({ children }) {
  return <tr>{children}</tr>;
}

function LeadCell({ children }) {
  return (
    <td className="px-4 py-1 text-sm font-medium text-gray-900 dark:text-gray-100 sm:text-base">
      {children}
    </td>
  );
}

function Cell({ children }) {
  return (
    <td className="px-4 py-1 text-sm text-gray-500 dark:text-gray-400 sm:text-base">
      {children}
    </td>
  );
}

export default function Resume() {
  return (
    <Layout pageTitle="Liquan's resume">
      <main className="block w-full space-y-8">
        <section>
          <Heading>Skills</Heading>
          <table className="min-w-full">
            <tbody>
              <TRow>
                <LeadCell>Languages</LeadCell>
                <Cell>Python, JavaScript, HTML/CSS, SQL, CypherQL, PHP</Cell>
              </TRow>
              <TRow>
                <LeadCell>Technologies</LeadCell>
                <Cell>
                  Docker, Hadoop, Tableau, Django, Flask, FastAPI, React, AWS,
                  GCP, Snowflake, Airflow
                </Cell>
              </TRow>
              <TRow>
                <LeadCell>Other</LeadCell>
                <Cell>
                  Relational & NoSQL databases, ML, Big data, API design, CI/CD
                </Cell>
              </TRow>
            </tbody>
          </table>
        </section>
        <section>
          <Heading>Work Experience</Heading>
          <div className="pl-4">
            <ExperienceList>
              {workExperience.map((job, idx) => (
                <ExperienceList.Item
                  key={idx}
                  primary={job.role}
                  secondary={job.company}
                  tertiary={job.location}
                  dates={job.dates}
                  descriptionList={job.descriptionList}
                />
              ))}
            </ExperienceList>
          </div>
        </section>
        <section>
          <Heading>Talks</Heading>
          <div className="pl-4">
            <ExperienceList>
              <ExperienceList.Item
                primary="Shiny, Prophet, and Video Game KPIs"
                secondary="Nordic DS & ML Summit"
                dates="2018/10"
              />
            </ExperienceList>
          </div>
        </section>
        <section>
          <Heading>Education & Training</Heading>
          <div className="pl-4">
            <ExperienceList>
              <ExperienceList.Item
                primary="Google Cloud Professional Machine Learning Engineer"
                tertiary={
                  <a href="https://www.credly.com/badges/4eba2e2a-7dae-4419-acac-a0241f8ecbf4/public_url">
                    View certificate
                  </a>
                }
                dates="2024/09"
              />
              <ExperienceList.Item
                primary="Google Cloud Professional Data Engineer"
                tertiary={
                  <a href="https://www.credly.com/badges/3888043a-78b5-47c8-ad84-d4a6c419d27a/public_url">
                    View certificate
                  </a>
                }
                dates="2023/01"
              />
              <ExperienceList.Item
                primary="React - The Complete Guide"
                secondary="Udemy"
                dates="2020/02"
              />
              <ExperienceList.Item
                primary="PyImageSearch Gurus"
                tertiary={
                  <a href="https://customers.pyimagesearch.com/certificates/pyimagesearch-gurus-certificate-of-completion/?course_id=386&cert-nonce=5316dc1334">
                    View certificate
                  </a>
                }
                dates="2018/06"
              />
              <ExperienceList.Item
                primary="Full Stack Web Development"
                tertiary={
                  <a href="https://www.coursera.org/account/accomplishments/specialization/ZQKJFGAZV64W">
                    View certificate
                  </a>
                }
                dates="2016/06"
              />
              <ExperienceList.Item
                primary="BS in Statistics"
                secondary="University of Florida"
                dates="2010/08"
              />
            </ExperienceList>
          </div>
        </section>
      </main>
    </Layout>
  );
}
